services:
  php:
    build:
      context: .
      dockerfile: php/Dockerfile  # Caminho para o Dockerfile dentro da pasta 'php'
    volumes:
      - ./app:/var/www/html  # Mapeia o código-fonte da aplicação
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/html  # Mapeia o código-fonte da aplicação
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf  # Configuração do NGINX
    depends_on:
      - php
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql  # Volume para dados do MySQL
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
    ports:
      - "3306:3306"
    networks:
      - app-network

  node:
    image: node:latest
    working_dir: /var/www/html
    volumes:
      - ./app:/var/www/html  # Mapeia o código-fonte da aplicação
    networks:
      - app-network

volumes:
  mysql-data:  # Define o volume persistente para o MySQL

networks:
  app-network:  # Define a rede personalizada para os serviços
